naam : Arta
leeftijd : 20
student : true 

hosts:
  - web1.example.com
  - web2.example.com
  - web3.example.com

dictionary:
  hosts: all
  vars: 
    app_port: 8080
  tasks: 
   - name: deplay app config
     template:
        src: app.conf .j2
        dest: /etc/app.conf
  
   